# NumPy (Numerical Python)

`NumPy` is a fundamental Python library used for **numerical computing**.  
It provides fast, memory-efficient data structures and mathematical operations that form the backbone of 
machine learning, data science, and scientific computing in Python.

Most ML libraries such as **scikit-learn, TensorFlow, PyTorch, Pandas** are built on top of NumPy.

---

## Why NumPy is Important in Machine Learning

NumPy enables:
- Fast mathematical computations  
- Efficient handling of large datasets  
- Vectorized operations (no explicit loops)  
- Linear algebra, statistics, and random sampling  

Without NumPy, ML algorithms would be extremely slow and memory-inefficient.



In [1]:
%%capture
!pip install numpy
import numpy as np


### Creating numpy/N-d arrays

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr6=np.arange(5,16,2)#(start,stop,step)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [9]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
arr1
arr1.shape
arr2
arr2.shape

(2, 3)

In [12]:
arr10=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr10


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
arr10.shape

(2, 2, 2)

In [14]:
arr10.ndim

3

In [15]:
arr11=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])

arr11

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [16]:
arr11.shape

(3, 2, 3)

In [17]:
arr11.ndim

3

In [18]:
arr12=np.array([
      [[11,12],[15,16,]]
])
arr12.itemsize

8

In [19]:
arr12.dtype

dtype('int64')

In [20]:
arr12.size

4

### Numpy arrays are better then python lists

In [21]:
lista=range(100)
arr20=np.arange(100)

In [22]:
import sys

In [23]:
print(sys.getsizeof(50)*len(lista))

2800


In [24]:
print(arr20.itemsize*arr20.size)

800


In [25]:
import time

In [26]:
x=range(10000000)
y=range(10000000,20000000)

start_time=time.time()
c=[(x,y) for x,y in zip(x,y)]
end_time=time.time()
print(end_time-start_time)

1.5199954509735107


In [27]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)

start_time=time.time()
c=a+b
end_time=time.time()
print(end_time-start_time)


0.49103569984436035


### Slicing

In [50]:
arr21=np.arange(30).reshape(6,5)
arr21

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [29]:
arr22=np.arange(5)
arr22

array([0, 1, 2, 3, 4])

In [30]:
arr22[2:4]


array([2, 3])

In [31]:
arr21[2] #3rd row of the matrix

array([10, 11, 12, 13, 14])

In [32]:
arr21[:,3] #:means all the rows

array([ 3,  8, 13, 18, 23, 28])

In [33]:
arr21[1:2] #1 is the start of slicing of row and 2 is the end before stop

array([[5, 6, 7, 8, 9]])

In [34]:
arr21[:,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [35]:
arr21[3:5,3:5]

array([[18, 19],
       [23, 24]])

### Iteration

In [51]:
for i in np.nditer(arr21):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


### Operation

In [52]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

arr1-arr2
arr1*2

array([ 2,  4,  6,  8, 10])

In [38]:
arr2>3

array([ True,  True,  True,  True,  True])

In [39]:
arr4=np.arange(6).reshape(2,3)
arr5=np.arange(6,12).reshape(3,2)

arr4.dot(arr5)#Normal matrix multiplication

array([[ 28,  31],
       [100, 112]])

In [40]:
arr5.max()
arr4.min()

np.int64(0)

In [41]:
arr4.min(axis=0)#Get the minimum elements from column by column
arr4.min(axis=1)#Get the minimum elements from row by row
arr4.sum(axis=1)
arr4.mean(axis=0)
arr4.std()
np.median(arr4)
np.sin(arr4)
np.exp(arr4)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

### Reshaping Numpy Array

In [42]:
arr4.ravel()#Converting multidimensional array into one dimensional array
arr4,np.transpose


(array([[0, 1, 2],
        [3, 4, 5]]),
 <function transpose at 0x000001FA7FCEAE30>)

In [43]:
arr5=np.arange(30,36).reshape(2,3)
arr5
np.hstack((arr4,arr5))#merging by row
np.vstack((arr4,arr5))#merging by cloumn
np.hsplit(arr4,3)
np.vsplit(arr4,2)


[array([[0, 1, 2]]), array([[3, 4, 5]])]

### Fancy Indexing

In [44]:
arr6=np.arange(36).reshape(6,6)
arr6[[0,2,4]]#To fetch the desired rows

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

### Indexing

In [45]:
arr7=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr7

array([[14, 64, 23, 35, 17],
       [14, 48, 82, 14, 93],
       [64, 43, 56, 18, 47],
       [66,  6, 10,  6, 91]], dtype=int32)

In [46]:
arr7<50

array([[ True, False,  True,  True,  True],
       [ True,  True, False,  True, False],
       [False,  True, False,  True,  True],
       [False,  True,  True,  True, False]])

In [47]:
arr7[arr7<50]
arr7[(arr7<50) & (arr7>20)]

array([23, 35, 48, 43, 47], dtype=int32)

In [48]:
arr7[(arr7<50) & (arr7>20)]=0
arr7

array([[14, 64,  0,  0, 17],
       [14,  0, 82, 14, 93],
       [64,  0, 56, 18,  0],
       [66,  6, 10,  6, 91]], dtype=int32)

In [ ]:
#Broadcasting(Make the smaller array to match with the bigger array)
#Equal dimensions: If the dimensions are the same, they are compatible.
#Dimension is 1: If one of the dimensions is 1, it can be broadcast (i.e., "stretched") to match the other.
#Missing dimensions: NumPy treats missing leading dimensions as 1 (i.e., it left-pads with 1s).

In [49]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])  # Shape: (2, 3)

B = np.array([10, 20, 30])  # Shape: (3,)

C = A + B  # Broadcasting B across each row of A
print(C)

[[11 22 33]
 [14 25 36]]


### NumPy Cheat Sheet for Data Science & ML

---

#### 1. Array Creation
- `np.array([1,2,3])`: Create array  
- `np.zeros(shape)`: Array of zeros  
- `np.ones(shape)`: Array of ones  
- `np.arange(start, stop, step)`: Range array  
- `np.linspace(start, stop, num)`: Evenly spaced numbers  
- `np.random.rand(n)`: Random floats  
- `np.random.randn(n)`: Random normal  
- `np.random.randint(low, high, size)`: Random integers  

---

#### 2. Array Inspection
- `arr.shape`: Dimensions  
- `arr.ndim`: Number of dimensions  
- `arr.size`: Total elements  
- `arr.dtype`: Data type  

---

#### 3. Array Operations
- `arr + x`, `arr - x`, `arr * x`: Element-wise operations  
- `np.add(a, b)`, `np.subtract(a, b)`, `np.multiply(a, b)`  
- `np.dot(a, b)`: Dot product  
- `np.matmul(a, b)`: Matrix multiplication  
- `arr.T`: Transpose  

---

#### 4. Indexing & Slicing
- `arr[i]`: Index  
- `arr[i:j]`: Slice  
- `arr[:, 0]`: Column  
- `arr[0, :]`: Row  
- Boolean indexing: `arr[arr > 5]`  

---

#### 5. Statistics & Math
- `np.mean(arr)`, `np.median(arr)`  
- `np.std(arr)`, `np.var(arr)`  
- `np.sum(arr)`, `np.min(arr)`, `np.max(arr)`  
- `np.argmin(arr)`, `np.argmax(arr)`  
- `np.percentile(arr, q)`  

---

#### 6. Reshaping & Manipulation
- `arr.reshape(shape)`  
- `arr.ravel()`: Flatten  
- `np.concatenate([a, b], axis)`  
- `np.vstack([a, b])`: Vertical stack  
- `np.hstack([a, b])`: Horizontal stack  

---

#### 7. Useful ML Operations
- `np.unique(arr)`: Unique values  
- `np.eye(n)`: Identity matrix  
- `np.where(condition, x, y)`: Conditional  
- `np.clip(arr, min, max)`: Limit values  
- `np.sqrt(arr)`, `np.exp(arr)`, `np.log(arr)`  

---

#### 8. Linear Algebra (Common in ML)
- `np.linalg.inv(A)`: Inverse  
- `np.linalg.det(A)`: Determinant  
- `np.linalg.eig(A)`: Eigenvalues + eigenvectors  
- `np.linalg.solve(A, b)`: Solve linear equations  

---

#### 9. Random Utilities (For ML)
- `np.random.seed(n)`: Reproducibility  
- `np.random.shuffle(arr)`: Shuffle  
- `np.random.choice(arr)`: Random choice  

