# Multiple Linear Regression

`Multiple Linear Regression` is an extension of Simple Linear Regression where the target variable is predicted
using **two or more independent variables**.  
It models the relationship between multiple features and a continuous target by fitting a linear equation.

---

## Model Representation

The Multiple Linear Regression model is defined as:

$$
\hat{y} = \theta_0 + \theta_1 x_1 + \theta_2 x_2 + \cdots + \theta_p x_p
$$

Where:
- $(\hat{y})$ = predicted value  
- $(x_1, x_2, \dots, x_p)$ = input features  
- $(\theta_0)$ = intercept (bias)  
- $(\theta_1, \theta_2, \dots, \theta_p)$ = model coefficients  
- $p$ = number of features  

---

## Objective Function (Loss Function)

Multiple Linear Regression typically minimizes **Mean Squared Error (MSE)**:

$$
J(\theta) =
\frac{1}{m} \sum_{i=1}^{m} (\hat{y}^{(i)} - y^{(i)})^2
$$

Where:
- $m$ = number of training samples  
- $y^{(i)}$ = actual value  
- $\hat{y}^{(i)}$ = predicted value  

---

## How the Model Learns

The parameters are estimated by:
- **Normal Equation** (closed-form solution)  
- **Gradient Descent** (iterative optimization)  

Both approaches aim to minimize the loss function.

---

## Assumptions of Multiple Linear Regression

Multiple Linear Regression assumes:
- Linear relationship between features and target  
- Independence of observations  
- Homoscedasticity (constant variance of errors)  
- Normal distribution of residuals  
- No strong multicollinearity between features  

Violating these assumptions can reduce model reliability.

---

## Multicollinearity

Multicollinearity occurs when input features are highly correlated.

Effects:
- Unstable coefficient estimates  
- Reduced interpretability  

Common solutions:
- Feature removal  
- Regularization (Ridge, Lasso, Elastic Net)  
- Dimensionality reduction (PCA)  

---

## When to Use Multiple Linear Regression

Multiple Linear Regression is suitable when:
- The target depends on multiple factors  
- Relationships are approximately linear  
- Interpretability is important  
- Dataset size is moderate  

---

## Advantages

- Simple and interpretable  
- Fast to train  
- Works well with structured tabular data  
- Provides clear feature importance via coefficients  

---

## Limitations

- Sensitive to outliers  
- Assumes linearity  
- Performance degrades with multicollinearity  
- Cannot model complex non-linear patterns  

---

## Example Use Cases

- Predicting house prices using size, location, and age  
- Estimating salary using education, experience, and skills  
- Forecasting sales using multiple marketing channels  

---

## Summary

Multiple Linear Regression models the relationship between multiple features and a continuous target using
a linear equation. It is a foundational algorithm in machine learning that balances simplicity,
interpretability, and performance for many real-world regression problems.


In [4]:
%%capture
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
from sklearn.datasets import load_diabetes

In [7]:
X,y = load_diabetes(return_X_y=True)

In [8]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [9]:
X.shape

(442, 10)

In [10]:
y.shape

(442,)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [12]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


### Creating Own Multiple Linear Regression Class

In [13]:
import numpy as np

class MyLR:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self, X_train, y_train):
        X_train = np.insert(X_train, 0, 1, axis=1)

        # Use pseudo-inverse (stable)
        betas = np.linalg.pinv(X_train).dot(y_train)

        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
    
    def predict(self, X_test):
        return np.dot(X_test, self.coef_) + self.intercept_


In [14]:
lr = MyLR()

In [15]:
lr.fit(X_train,y_train)

In [16]:
X_train.shape

(353, 10)

In [17]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

In [18]:
y_pred = lr.predict(X_test)

In [19]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.43993386615689645

In [20]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [21]:
lr.intercept_

np.float64(151.8833100525407)

### Scikit-Learn Built-in Linear Regression Class

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
reg = LinearRegression()

In [24]:
reg.fit(X_train,y_train)

LinearRegression()

In [25]:
y_pred = reg.predict(X_test)

In [26]:
r2_score(y_test,y_pred)

0.4399338661568968

In [27]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [28]:
reg.intercept_

np.float64(151.88331005254167)